### ISSUE TITLE
ndt7: test stalls right after connect

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-cloud#37]
This issue has been noted by me two weeks ago, but I thought it was caused by the fact that I was testing with a 2G mobile. However, we run some more tests with @mattmathis recently and we did see that it was actually a systematic issue. I tracked down the problem to the server being stuck trying to `Hijack` the connection, as shown by the following stacktrace obtained using `SIGQUIT` (I was using go1.11.0 at the time; upgrading to go1.11.2 only made the problem deterministic):

```
2018/11/09 19:57:37 About to listen on 3010. Go to http://127.0.0.1:3010/
93.67.200.68 - - [09/Nov/2018:19:57:42 +0000] "GET /static/ndt7.html HTTP/2.0" 200 2876
93.67.200.68 - - [09/Nov/2018:19:57:42 +0000] "GET /static/ndt7-worker.js HTTP/2.0" 200 1373
93.67.200.68 - - [09/Nov/2018:19:57:42 +0000] "GET /favicon.ico HTTP/2.0" 200 165
93.67.200.68 - - [09/Nov/2018:19:57:42 +0000] "GET /static/libndt7.js HTTP/2.0" 200 4260
{"fields":{},"level":"debug","timestamp":"2018-11-09T19:57:43.504240955Z","message":"Upgrading to WebSockets"}
{"fields":{},"level":"debug","timestamp":"2018-11-09T19:57:43.504608334Z","message":"Got Sec-WebSocket-Protocol header"}
SIGQUIT: quit
PC=0x4613e1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x1045c00, 0x80, 0x0, 0x0, 0x0, 0x1864fc0, 0x0, 0x0, 0x7ffc408781d0, 0x40bd12, ...)
	/home/sbs/src/github.com/golang/go/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0x1045c00, 0x0, 0xffffffffffffffff)
	/home/sbs/src/github.com/golang/go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x1045c00)
	/home/sbs/src/github.com/golang/go/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
	/home/sbs/src/github.com/golang/go/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc000032f00, 0x0)
	/home/sbs/src/github.com/golang/go/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
	/home/sbs/src/github.com/golang/go/src/runtime/proc.go:2613 +0x13a
runtime.park_m(0xc000001c80)
	/home/sbs/src/github.com/golang/go/src/runtime/proc.go:2676 +0xae
runtime.mcall(0xa1c730)
	/home/sbs/src/github.com/golang/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fe5040fdf00, 0x72, 0xc0001fb7c0)
	/home/sbs/src/github.com/golang/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000190118, 0x72, 0x0, 0x0, 0xc5c220)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_poll_runtime.go:85 +0xe4
internal/poll.(*pollDesc).waitRead(0xc000190118, 0xffffffffffffff00, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_poll_runtime.go:90 +0x4b
internal/poll.(*FD).Accept(0xc000190100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_unix.go:384 +0x27f
net.(*netFD).accept(0xc000190100, 0x149744af9, 0x0, 0xc0003521e0)
	/home/sbs/src/github.com/golang/go/src/net/fd_unix.go:238 +0x53
net.(*TCPListener).accept(0xc000154080, 0x8, 0x0, 0xc000070a80)
	/home/sbs/src/github.com/golang/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).AcceptTCP(0xc000154080, 0x40ce17, 0xc000070a80, 0x380)
	/home/sbs/src/github.com/golang/go/src/net/tcpsock.go:247 +0x50
main.tcpListenerEx.Accept(0xc000154080, 0x1, 0xc0001528b0, 0xc0001fbab0, 0x43dd7a, 0xc000000300)
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt-server.go:127 +0x3d
crypto/tls.(*listener).Accept(0xc00016be20, 0x460adc, 0x43727e, 0xc0001fbb70, 0x45c410)
	/home/sbs/src/github.com/golang/go/src/crypto/tls/tls.go:52 +0x55
net/http.(*Server).Serve(0xc000152820, 0xc5f040, 0xc00016be20, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2826 +0x358
net/http.(*Server).ServeTLS(0xc000152820, 0xc5f940, 0xc00015a920, 0x7ffc408788a8, 0x8, 0x7ffc408788b6, 0x7, 0xbb75e0, 0x4)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2891 +0x3a5
main.main()
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt-server.go:700 +0x795

goroutine 50 [syscall]:
os/signal.signal_recv(0x45f0e1)
	/home/sbs/src/github.com/golang/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/sbs/src/github.com/golang/go/src/os/signal/signal_unix.go:23 +0x30
created by os/signal.init.0
	/home/sbs/src/github.com/golang/go/src/os/signal/signal_unix.go:29 +0x4f

goroutine 55 [IO wait]:
internal/poll.runtime_pollWait(0x7fe5040fde30, 0x72, 0xc000051ae8)
	/home/sbs/src/github.com/golang/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0001cc018, 0x72, 0x0, 0x0, 0xc5c220)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_poll_runtime.go:85 +0xe4
internal/poll.(*pollDesc).waitRead(0xc0001cc018, 0xffffffffffffff00, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_poll_runtime.go:90 +0x4b
internal/poll.(*FD).Accept(0xc0001cc000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_unix.go:384 +0x27f
net.(*netFD).accept(0xc0001cc000, 0x50, 0x50, 0x43d9ff)
	/home/sbs/src/github.com/golang/go/src/net/fd_unix.go:238 +0x53
net.(*TCPListener).accept(0xc00000e058, 0xc000051d58, 0x40ce17, 0xc00013c570)
	/home/sbs/src/github.com/golang/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).AcceptTCP(0xc00000e058, 0x0, 0xc000051d60, 0xc0001ca090)
	/home/sbs/src/github.com/golang/go/src/net/tcpsock.go:247 +0x50
net/http.tcpKeepAliveListener.Accept(0xc00000e058, 0x1006501, 0xc00013c570, 0xc000051dc0, 0x518abe)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:3232 +0x3d
net/http.(*Server).Serve(0xc0001ca000, 0xc5fa80, 0xc00000e058, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2826 +0x358
net/http.(*Server).ListenAndServe(0xc0001ca000, 0xc8, 0xc0001b2128)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2764 +0xe9
net/http.ListenAndServe(0xbb7d0e, 0x5, 0xc5b280, 0xc00013c120, 0xc00013c420, 0x0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:3004 +0xf0
main.main.func1()
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt-server.go:676 +0x1c1
created by main.main
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt-server.go:668 +0x78

goroutine 54 [chan receive]:
main.catchSigterm()
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt-server.go:659 +0x186
created by main.main
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt-server.go:667 +0x60

goroutine 56 [IO wait]:
internal/poll.runtime_pollWait(0x7fe5040fdd60, 0x72, 0xc0002098b0)
	/home/sbs/src/github.com/golang/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0001cc098, 0x72, 0x0, 0x0, 0xc5c220)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_poll_runtime.go:85 +0xe4
internal/poll.(*pollDesc).waitRead(0xc0001cc098, 0xffffffffffffff00, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_poll_runtime.go:90 +0x4b
internal/poll.(*FD).Accept(0xc0001cc080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_unix.go:384 +0x27f
net.(*netFD).accept(0xc0001cc080, 0x460a32, 0xc000052ab0, 0x4b9cfa)
	/home/sbs/src/github.com/golang/go/src/net/fd_unix.go:238 +0x53
net.(*TCPListener).accept(0xc00000e068, 0x8, 0xc00001e690, 0xc00013cae0)
	/home/sbs/src/github.com/golang/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).AcceptTCP(0xc00000e068, 0x40ce17, 0xc00013cae0, 0x30)
	/home/sbs/src/github.com/golang/go/src/net/tcpsock.go:247 +0x50
net/http.tcpKeepAliveListener.Accept(0xc00000e068, 0xc00013cae0, 0x0, 0xc000042700, 0x43d0fc)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:3232 +0x3d
crypto/tls.(*listener).Accept(0xc00000d000, 0x1006501, 0xc00013cae0, 0xc000209bf8, 0x518abe)
	/home/sbs/src/github.com/golang/go/src/crypto/tls/tls.go:52 +0x55
net/http.(*Server).Serve(0xc0001ca1a0, 0xc5f040, 0xc00000d000, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2826 +0x358
net/http.(*Server).ServeTLS(0xc0001ca1a0, 0xc5fa80, 0xc00000e068, 0x7ffc408788a8, 0x8, 0x7ffc408788b6, 0x7, 0x0, 0xba8280)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2891 +0x3a5
net/http.(*Server).ListenAndServeTLS(0xc0001ca1a0, 0x7ffc408788a8, 0x8, 0x7ffc408788b6, 0x7, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:3048 +0x15e
net/http.ListenAndServeTLS(0xc0000260d8, 0x5, 0x7ffc408788a8, 0x8, 0x7ffc408788b6, 0x7, 0x0, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:3014 +0x128
main.main.func2()
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt-server.go:690 +0x161
created by main.main
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt-server.go:689 +0x250

goroutine 57 [select]:
net/http.(*http2serverConn).serve(0xc000182380)
	/home/sbs/src/github.com/golang/go/src/net/http/h2_bundle.go:4600 +0x920
net/http.(*http2Server).ServeConn(0xc000176300, 0xc62900, 0xc000184a80, 0xc0000abc28)
	/home/sbs/src/github.com/golang/go/src/net/http/h2_bundle.go:4219 +0xd51
net/http.http2ConfigureServer.func1(0xc000152820, 0xc000184a80, 0xc5c020, 0xc00015b0b0)
	/home/sbs/src/github.com/golang/go/src/net/http/h2_bundle.go:4057 +0xb9
net/http.(*conn).serve(0xc000170b40, 0xc5fd80, 0xc000157230)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:1771 +0x182d
created by net/http.(*Server).Serve
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2851 +0x4c6

goroutine 61 [syscall]:
syscall.Syscall(0x0, 0x7, 0xc0001a5800, 0x400, 0x460b8c, 0x4abcab, 0x460a32)
	/home/sbs/src/github.com/golang/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x7, 0xc0001a5800, 0x400, 0x400, 0x72, 0x42ca00, 0x0)
	/home/sbs/src/github.com/golang/go/src/syscall/zsyscall_linux_amd64.go:732 +0x68
syscall.Read(0x7, 0xc0001a5800, 0x400, 0x400, 0xc0002b4500, 0xc0002875b8, 0x414dac)
	/home/sbs/src/github.com/golang/go/src/syscall/syscall_unix.go:172 +0x5b
internal/poll.(*FD).Read(0xc000190180, 0xc0001a5800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_unix.go:165 +0x195
net.(*netFD).Read(0xc000190180, 0xc0001a5800, 0x400, 0x400, 0xc000178a00, 0x500, 0xc000178a00)
	/home/sbs/src/github.com/golang/go/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc0001540a0, 0xc0001a5800, 0x400, 0x400, 0x0, 0xc000174f00, 0x280)
	/home/sbs/src/github.com/golang/go/src/net/net.go:177 +0xa1
crypto/tls.(*block).readFromUntil(0xc000157320, 0xc5b220, 0xc0001540a0, 0x5, 0xc0001540a0, 0xc000178a00)
	/home/sbs/src/github.com/golang/go/src/crypto/tls/conn.go:492 +0x107
crypto/tls.(*Conn).readRecord(0xc000184a80, 0xbdae17, 0xc000184ba0, 0xc000032f00)
	/home/sbs/src/github.com/golang/go/src/crypto/tls/conn.go:593 +0x132
crypto/tls.(*Conn).Read(0xc000184a80, 0xc00020a1f8, 0x9, 0x9, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/crypto/tls/conn.go:1145 +0x15f
io.ReadAtLeast(0x7fe5040791f8, 0xc000184a80, 0xc00020a1f8, 0x9, 0x9, 0x9, 0xc000176568, 0xc000176560, 0xc000176558)
	/home/sbs/src/github.com/golang/go/src/io/io.go:310 +0x96
io.ReadFull(0x7fe5040791f8, 0xc000184a80, 0xc00020a1f8, 0x9, 0x9, 0x45c667, 0xc000287f78, 0x42fc2c)
	/home/sbs/src/github.com/golang/go/src/io/io.go:329 +0x73
net/http.http2readFrameHeader(0xc00020a1f8, 0x9, 0x9, 0x7fe5040791f8, 0xc000184a80, 0x0, 0xc000000000, 0x2, 0x2)
	/home/sbs/src/github.com/golang/go/src/net/http/h2_bundle.go:1545 +0xa3
net/http.(*http2Framer).ReadFrame(0xc00020a1c0, 0xc000287eb0, 0x2, 0x0, 0x1)
	/home/sbs/src/github.com/golang/go/src/net/http/h2_bundle.go:1803 +0x10e
net/http.(*http2serverConn).readFrames(0xc000182380)
	/home/sbs/src/github.com/golang/go/src/net/http/h2_bundle.go:4487 +0xfa
created by net/http.(*http2serverConn).serve
	/home/sbs/src/github.com/golang/go/src/net/http/h2_bundle.go:4592 +0x5a4

goroutine 29 [syscall]:
syscall.Syscall(0x0, 0xa, 0xc00037d400, 0x400, 0x460b8c, 0x4abcab, 0x460a32)
	/home/sbs/src/github.com/golang/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xa, 0xc00037d400, 0x400, 0x400, 0x72, 0x42ca00, 0x0)
	/home/sbs/src/github.com/golang/go/src/syscall/zsyscall_linux_amd64.go:732 +0x68
syscall.Read(0xa, 0xc00037d400, 0x400, 0x400, 0x2000, 0x10ca, 0x0)
	/home/sbs/src/github.com/golang/go/src/syscall/syscall_unix.go:172 +0x5b
internal/poll.(*FD).Read(0xc0002bc500, 0xc00037d400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/internal/poll/fd_unix.go:165 +0x195
net.(*netFD).Read(0xc0002bc500, 0xc00037d400, 0x400, 0x400, 0x10ca, 0x2000, 0x10ca)
	/home/sbs/src/github.com/golang/go/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc0002c4028, 0xc00037d400, 0x400, 0x400, 0x10ca, 0xc00024ead0, 0x42d371)
	/home/sbs/src/github.com/golang/go/src/net/net.go:177 +0xa1
crypto/tls.(*block).readFromUntil(0xc00013e990, 0xc5b220, 0xc0002c4028, 0x5, 0xc0002c4028, 0x3)
	/home/sbs/src/github.com/golang/go/src/crypto/tls/conn.go:492 +0x107
crypto/tls.(*Conn).readRecord(0xc000070a80, 0xbdae17, 0xc000070ba0, 0x3)
	/home/sbs/src/github.com/golang/go/src/crypto/tls/conn.go:593 +0x132
crypto/tls.(*Conn).Read(0xc000070a80, 0xc00013ea01, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/crypto/tls/conn.go:1145 +0x15f
net/http.(*connReader).backgroundRead(0xc00013e9f0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:676 +0xa5
created by net/http.(*connReader).startBackgroundRead
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:672 +0x14a

goroutine 28 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc000148650, 0x0)
	/home/sbs/src/github.com/golang/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc000148640)
	/home/sbs/src/github.com/golang/go/src/sync/cond.go:56 +0x8e
net/http.(*connReader).abortPendingRead(0xc00013e9f0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:724 +0x15c
net/http.(*conn).hijackLocked(0xc0002a4280, 0xbdaea0, 0xc0002a4308, 0x503100, 0xc000391220, 0x40b2e8)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:313 +0xa5
net/http.(*response).Hijack(0xc000386000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:1914 +0xfc
github.com/gorilla/handlers.(*hijackLogger).Hijack(0xc0001462a0, 0x7fe50403d0d0, 0xc0002ae7a0, 0xc000391300, 0x7fe50403d0d0, 0xc00013ea50)
	/home/sbs/src/github.com/gorilla/handlers/handlers.go:90 +0x79
github.com/gorilla/websocket.(*Upgrader).Upgrade(0xc000391650, 0x7fe50403d060, 0xc00013eae0, 0xc0002be800, 0xc000391620, 0x1044908, 0x43d1ab, 0x43d225)
	/home/sbs/src/github.com/gorilla/websocket/server.go:178 +0x468
github.com/m-lab/ndt-cloud/ndt7.DownloadHandler.ServeHTTP(0x7fe50403d060, 0xc00013eae0, 0xc0002be800)
	/home/sbs/src/github.com/m-lab/ndt-cloud/ndt7/server.go:165 +0x269
net/http.(*ServeMux).ServeHTTP(0x1044900, 0x7fe50403d060, 0xc00013eae0, 0xc0002be800)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2361 +0x192
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xc5b5c0, 0xc0000a2008, 0xc5b280, 0x1044900, 0xbda088, 0xc5f640, 0xc000386000, 0xc0002be800)
	/home/sbs/src/github.com/gorilla/handlers/logging.go:45 +0x18d
net/http.serverHandler.ServeHTTP(0xc000152820, 0xc5f640, 0xc000386000, 0xc0002be800)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2741 +0xc5
net/http.(*conn).serve(0xc0002a4280, 0xc5fcc0, 0xc000148600)
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:1847 +0x80b
created by net/http.(*Server).Serve
	/home/sbs/src/github.com/golang/go/src/net/http/server.go:2851 +0x4c6

rax    0xca
rbx    0x1045ac0
rcx    0x4613e3
rdx    0x0
rdi    0x1045c00
rsi    0x80
rbp    0x7ffc40878198
rsp    0x7ffc40878150
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc0000ab090
r13    0x1045ac0
r14    0xc000001380
r15    0x0
rip    0x4613e1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

I did run some experiments trying to understand the trigger. As mentioned, my first attempt was to upgrade go1.11.0 to go1.11.2 assuming it could be I was hitting a later-fixed bug. It didn't work.

Then, my second attempt was at fully disabling the fdcache and enabling BBR. That fixed.

Then, the third attempt was just disabling enabling BBR. That fixed.

So, in the fourth attempt, I _moved_ the BBR enabling code from right after connect to when we're in full control of the WebSocket stream. That fixed as well. The fixing (non minimal) diff is:

```diff
diff --git a/build.sh b/build.sh
index b4d88cc..ce92a43 100755
--- a/build.sh
+++ b/build.sh
@@ -4,7 +4,7 @@ set -ex
 TOPDIR=`cd $(dirname $0) && pwd -P`
 cd $TOPDIR
 VERSION=`git describe --tags`
-go get -v                                                              \
+go get -race -u -v                                                     \
     -tags netgo                                                        \
     -ldflags "-X github.com/m-lab/ndt-cloud/version.Version=$VERSION"  \
     .
diff --git a/ndt-server.go b/ndt-server.go
index a0fee57..31ab90d 100644
--- a/ndt-server.go
+++ b/ndt-server.go
@@ -17,7 +17,6 @@ import (
 	"time"
 
 	"github.com/gorilla/websocket"
-	"github.com/m-lab/ndt-cloud/bbr"
 	"github.com/m-lab/ndt-cloud/fdcache"
 	"github.com/m-lab/ndt-cloud/ndt7"
 	"github.com/prometheus/client_golang/prometheus"
@@ -135,20 +134,6 @@ func (ln tcpListenerEx) Accept() (net.Conn, error) {
 		tc.Close()
 		return nil, err
 	}
-	if ln.TryToEnableBBR {
-		err = bbr.Enable(fp)
-		if err != nil && err != bbr.ErrNoSupport {
-			log.Printf("Cannot initialize BBR: %s", err.Error())
-			// We need to close both because fp is a dup() of the original tc.
-			fp.Close()
-			tc.Close()
-			return nil, err
-		}
-		if err == bbr.ErrNoSupport {
-			// Keep going. There are also old Linux servers without BBR and servers
-			// where the operating system is different from Linux.
-		}
-	}
 	// Transfer ownership of |fp| to fdcache so that later we can retrieve
 	// it from the generic net.Conn object bound to a websocket.Conn.
 	fdcache.OwnFile(tc, fp)
diff --git a/ndt7/server.go b/ndt7/server.go
index b424aca..2d8a893 100644
--- a/ndt7/server.go
+++ b/ndt7/server.go
@@ -21,7 +21,6 @@ const defaultDuration = 10 * time.Second
 
 // DownloadHandler handles a download subtest from the server side.
 type DownloadHandler struct {
-	Upgrader websocket.Upgrader
 }
 
 // stableAccordingToBBR returns true when we can stop the current download
@@ -157,9 +156,13 @@ func (dl DownloadHandler) ServeHTTP(writer http.ResponseWriter, request *http.Re
 		warnAndClose(writer, "Missing Sec-WebSocket-Protocol in request")
 		return
 	}
+	ErrorLogger.Debug("Got Sec-WebSocket-Protocol header")
 	headers := http.Header{}
 	headers.Add("Sec-WebSocket-Protocol", SecWebSocketProtocol)
-	conn, err := dl.Upgrader.Upgrade(writer, request, headers)
+	upgrader := websocket.Upgrader{
+		HandshakeTimeout: defaultTimeout,
+	}
+	conn, err := upgrader.Upgrade(writer, request, headers)
 	if err != nil {
 		warnAndClose(writer, "Cannnot UPGRADE to WebSocket")
 		return
@@ -190,6 +193,7 @@ func (dl DownloadHandler) ServeHTTP(writer http.ResponseWriter, request *http.Re
 	// to program defensively rather than calling panic() here.
 	if fp != nil {
 		defer fp.Close()  // We own `fp` and we must close it when done
+		bbr.Enable(fp)
 	}
 	// TODO(bassosimone): an error before this point means that the *os.File
 	// will stay in cache until the cache pruning mechanism is triggered. This

```

I wonder what is going on. Now I've to stop debugging to go and catch my flight :-).

**Comment by bassosimone** [comment]
So, we agreed with @pboothe that an initial good-enough step is to just apply the above fix and start rolling out the experiment. We'll investigate this further at a later stage.
